library(usethis)
use_description()
use_directory("DEV", ignore = TRUE)
use_data_raw()
use_mit_license("Johan van Tent")
use_news_md()
use_readme_rmd()
use_roxygen_md()
use_namespace()
use_package("dplyr")
use_package("tidyr")
#use_package("readr")
use_package("purrr")
use_package("stringr")
use_package("tibble")
use_travis()
use_coverage()
use_version()
